### ISSUE TITLE
How to set and get cookie in store ?

### ISSUE THREAD

**Issue by kousar2334** [microcipcip/cookie-universal#100]

**Comment by shawnlauzon** [comment]
See #9 and #17 -- do they answer your question?

I thought I needed to get and set in the store, and eventually realized that it was better in my case to use them outside the store.

**Comment by shawnlauzon** [comment]
Also `this.$cookies` is defined in the store.

**Comment by macleash90** [comment]
Try changing to Serverside rendering in your nuxt.config.js, inside export default{} add/modify to this
`ssr: true,`

Hope this helps someone in the future
