### ISSUE TITLE
this.$cooike not undefind

### ISSUE THREAD

**Issue by a982246809** [microcipcip/cookie-universal#101]
![image](https://user-images.githubusercontent.com/56909676/115322611-0cc21600-a1b9-11eb-8bb7-6e61b1a1d890.png)

**Comment by RHellenes** [comment]
Have you doublechecked that you have spelled `this.$cookies` and not `this.$cooike` as you have in the title :)
Also am using Nuxt, and the $cookies is listed further down, where the purple is a bit darker, it might be listed there for you aswell.

**Comment by Triloworld** [comment]
In documentation there is error:
<img width="603" alt="Zrzut ekranu 2021-05-22 o 16 52 09" src="https://user-images.githubusercontent.com/2671726/119230820-1e7f3c00-bb1e-11eb-9ecb-e3605d0d91fd.png">

Pleas be sure that ```app``` is populated with data and module is properly enabled.
Tested today on latest version

**Comment by microcipcip** [comment]
@Triloworld sorry if the documentation is confusing, `cookiz` is just an example of exposing cookieUniversalNuxt with a different alias.
