### ISSUE TITLE
Cannot set cookies on client when `httpOnly` is set on `true`

### ISSUE THREAD

**Issue by kylemod** [microcipcip/cookie-universal#107]
`$cookies.set('token', 'apikey')` = works on client

`$cookies.set('token','apikey', { httpOnly: true} )` = doesn't work in client

And it works on server like `nuxtServerInit`

**Comment by microcipcip** [comment]
Hi @kylemod, you can't set, edit or delete a cookie that has httpOnly set to true. That is a browser security limitation. A `httpOnly` cookie can only be set server side. Hope this answer your question.
