### ISSUE TITLE
Typings for Nuxt 2.15

### ISSUE THREAD

**Issue by akadlec** [microcipcip/cookie-universal#109]
Is possible to extend typings for latest Nuxt version? There is context definition missing

```ts
declare module '@nuxt/types' {
  interface NuxtAppOptions {
    $cookies: NuxtCookies;
  }

  interface Context {
    $cookies: NuxtCookies;
  }
}
```

**Comment by adinvadim** [comment]
Create in your project

types/cookiie-universal-nuxt.d.ts

```typescript
import { NuxtCookies } from 'cookie-universal-nuxt';

declare module '@nuxt/types' {
  interface Context {
    $cookies: NuxtCookies;
  }
}
```

And add       "./types" to the types in tsconfig

**Comment by akadlec** [comment]
this solution I'm using right now, but it would be cleaner to have it in library

**Comment by microcipcip** [comment]
So I just need to add the code below [here](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal-nuxt/types/index.d.ts#L41)?
```ts
 interface Context {
    $cookies: NuxtCookies;
  }
```

**Comment by akadlec** [comment]
Yes

**Comment by microcipcip** [comment]
@akadlec I've just finished updating the lib with these type definitions. Let me know if now it works fine.

**Comment by akadlec** [comment]
@microcipcip works great, thanks
