### ISSUE TITLE
Can't get 'headers' of undefined

### ISSUE THREAD

**Issue by longhoang2984** [microcipcip/cookie-universal#11]
Hi @microcipcip ,

I have issues like the title when I run 'nuxt generate'

**Comment by microcipcip** [comment]
It seems that the req object is `undefined` when using nuxt generate. I have found [this related issue](https://github.com/nuxt/nuxt.js/issues/1123#issuecomment-316788645)... I think I need to disable it if both req and res are undefined.

**Comment by longhoang2984** [comment]
Hi @microcipcip ,

Thanks for your fast responding. 

I hope it will done asap <3

**Comment by microcipcip** [comment]
@longhoang2984 I think I have fixed the error. Try to upgrade :)
