### ISSUE TITLE
Can't read cookie after set

### ISSUE THREAD

**Issue by Bacher** [microcipcip/cookie-universal#113]
I try to use `cookie-universal` on backend.

This code doesn't work as expected:

```javascript
const cookieUniversal = require('cookie-universal');

// this code in handler:
const cookieManager = cookieUniversal(req, res);

cookieManager.set('test', 'value');

console.log('Cookie value:', cookieManager.get('test')); // => Cookie value: undefined
```

You could try without req&res here: [https://runkit.com/embed/5mbjvll59vpp](https://runkit.com/embed/5mbjvll59vpp), issue is still here:
```javascript
const cookieUniversal = require("cookie-universal")

const cookieManager = cookieUniversal(false, false);

cookieManager.set('test', 'value', { path: '/', maxAge: 1800 });

cookieManager.get('test'); // => Cookie is empty
```

**Comment by microcipcip** [comment]
I need more info, did you try this on a server or in the client? I am particularly interested in where you called this line: `cookieManager.get('test');`. You can't read the cookie until is sent to the client.

**Comment by Bacher** [comment]
I understand how it works, but it is not intuitive anyway.

I have tried use this library for managering cookies on SSR part, when SSR server makes several continues request into real-backend, and after first response from backend I wanted to use new cookie to make sequential requests to the same backend. And after all send all new cookies to user back.

**Comment by microcipcip** [comment]
You can read from the response with the `fromRes` option, if that is what you are looking for. But it won't read from `res` automatically, that is not how usually cookies are read in the server.
```js
cookieManager.get('test', { fromRes: true }));
```

**Comment by Bacher** [comment]
Ok, thank you.

**Comment by upsilon** [comment]
I'm still confused by this issue. 

I understand that I can get unsent cookies by `fromRes` option on the server, but I always have to merge the two cookie sets to get the same behavior in the code that shared with the browser.
Is there a more universal way to get cookies?

```js
// In browser... (expected behavior)
cookies.set('test', new Date().getTime())
console.log(cookies.getAll()) // This includes 'test' cookie
cookies.remove('test')
console.log(cookies.getAll()) // This does not include 'test' cookie

// In server...
cookies.set('test', new Date().getTime())
// I have to merge two cookie sets to get same results as browser
console.log({...cookies.getAll(), ...cookies.getAll({fromRes: true})}) 

cookies.remove('test')
// But in this situation, 'test' is still included unlike the browser.
console.log({...cookies.getAll(), ...cookies.getAll({fromRes: true})}) 
```
