### ISSUE TITLE
removeAll documentation

### ISSUE THREAD

**Issue by Tobeyforce** [microcipcip/cookie-universal#114]
I think it would be greatly appreciated if you could document a little bit more on how removeAll() works with some examples, my current interpretation is that you can just give it an array of strings, but could you do more? E.g hand it an array of objects, e.g with path etc.
My use case is that I want to be able to remove all cookies from one particular path/domain in one function call. E.g, the user opts out of facebook pixel -> opt out of facebook pixel and remove all the cookies for it.

**Comment by Tobeyforce** [comment]
Actually I realize that removeAll() does exactly that, removes every single cookie. Is there any way to remove multiple cookies in one call, without running a forloop with remove()?

**Comment by microcipcip** [comment]
@Tobeyforce, so what you would like to do is something like this, right?

```js
cookies.removeAll({ path: '/specific/path' })
```

**Comment by Tobeyforce** [comment]
> @Tobeyforce, so what you would like to do is something like this, right?
> 
> ```js
> cookies.removeAll({ path: '/specific/path' })
> ```

Exactly, that would be excellent. Sorry for the late reply!
