### ISSUE TITLE
Migration to ESM

### ISSUE THREAD

**Issue by james-camilleri** [microcipcip/cookie-universal#118]
This package is being used by https://github.com/beyonk-adventures/gdpr-cookie-consent-banner, which I'm helping make SvelteKit compatible through migration to ESM import/export syntax. Since this module is a dependency however, it still trips up without any additional workarounds (although it can be worked around to some extent).

Would it be possible to have this package be compatible with ESM modules? I'd be willing to submit a PR myself if you're open to it.

**Comment by microcipcip** [comment]
@james-camilleri sorry I don't get notifications lately, yes I would accept PR for adding the compatibility.
