### ISSUE TITLE
Can I remove cookie by domain option?

### ISSUE THREAD

**Issue by Bombay** [microcipcip/cookie-universal#12]
Hi.

Can I remove cookie by domain option?

I want to give remove option domain not path

Thank you for great module

**Comment by microcipcip** [comment]
Can you be more specific? Is the cookie in a different domain? For security reasons you can't delete a cookie from another domain. See [this issue on stackoverflow](https://stackoverflow.com/a/17777005/974107).

**Comment by Bombay** [comment]
My project created a cookie domain ".domain.com" to be intentionally shared on the same domain.
I want to use it once on a particular server with the same domain and try to delete it.

It is okay if it is an unreasonable request. Thank you very much for your quick reply.

**Comment by microcipcip** [comment]
If the server is different but the domain is the same you should be able to remove it. The only option you can specify when deleting is the `path` parameter, so if you get that right it should work. I am not sure if you can delete it if it is a subdomain though.

**Comment by microcipcip** [comment]
You can do anything that you are allowed to do with the [node cookie script](https://github.com/jshttp/cookie), because I just extend it.

**Comment by Bombay** [comment]
I deleted it in the following way, but I wanted to integrate it using your plugin.

//in nuxt middleware
let cookieString = `$ {key} =; expire = $ {expiredDate} domain = $ {domain}
if(isServer) res.setHeader('Set-Cookie', cookieString)
else document.cookie = cookieString

However, my case is a special case, and this method seems to be a security problem, so it does not seem to be necessary to add the function. Thanks for the answer.

**Comment by microcipcip** [comment]
Ok, I'll close it for now. I think the following should be the same of your code above.
```
cookies.set(key, '', {
  expires: expiredDate,
  domain: domain
})
```
