### ISSUE TITLE
[Docs/FeatureRequest?] Vuex Examples / Integration

### ISSUE THREAD

**Issue by gbezyuk** [microcipcip/cookie-universal#16]
How should I use $cookies inside Vuex actions?

**Comment by microcipcip** [comment]
@gbezyuk are you using Vuex or Nuxt? With Vuex you either create a global Vue mixin to have it conveniently available globally or you just use it like this:
```
// import it at the top of the Vuex file
import Cookie from 'cookie-universal'

Initialize it
const cookies = Cookie()

// use it anywhere inside mutations, actions, etc
cookies.set('cookie-name', 'cookie-value')
```

**Comment by microcipcip** [comment]
@gbezyuk I am closing this issue for the lack of feedback, but please feel free to reopen it if you are still having problems!
