### ISSUE TITLE
Breaks in Internet Exlorer 11. Doesn't get transpiled?

### ISSUE THREAD

**Issue by FransTwisk** [microcipcip/cookie-universal#2]
Seems the module somehow doesn't get transpiled and thus breaks in IE11. Using this in the latest Nuxt.js (v2.3.0).

![image](https://user-images.githubusercontent.com/76724/36503265-ccccf9c4-174c-11e8-97cb-f418ee57a410.png)

Not sure if this is a problem with the module or with Nuxt itself, don't have any problems with other modules I use.

**Comment by microcipcip** [comment]
Thanks a lot, it's the first time that I publish a module so I didn't know that node_modules don't get transpiled. I have added a `dist/cookie-universal-common.js` file, if you remove it from package.json and add it back it should now work on IE...hopefully.

**Comment by FransTwisk** [comment]
Gotta start somewhere :) Great work on the module though, seems to be the only one really working correct just out of the box. I'll try the new version later today and let you know.

**Comment by FransTwisk** [comment]
Just tested the new version on IE11, works great! This also fixes it in some older iOS / Android browsers.
