### ISSUE TITLE
On the server `cookie.get` should return what is `cookie.set`

### ISSUE THREAD

**Issue by desislavsd** [microcipcip/cookie-universal#20]
Can you make cookies dynamic on the server, so that the following would work:

```javascript
   // set foo for the very first time
   cookie.set('foo', 123); // the cookie will be set on the client once the page is served
   
   cookie.get('foo') // returns undefined ; expected 123
```
I know it will be a bit hacky but I think it is useful.

Regards :}

**Comment by microcipcip** [comment]
So you want to get the cookie that you just set, directly in the server, right?
Try to add the fromRes option:
```
cookie.get('foo', { fromRes: true });
```

**Comment by desislavsd** [comment]
Oh, I see! Please, forgive my negligence!
