### ISSUE TITLE
plugin working on the localhost, not working on production !! 

### ISSUE THREAD

**Issue by maverickpravin** [microcipcip/cookie-universal#21]
Thanks for this easy plugin for nuxt, i am using this plugin in my important project. 
My question is that, the plugin is working fine on my localhost, but when i take for build in the production, its stops working ( does not delete the cookies ). Any ideas ???

**Comment by maverickpravin** [comment]
this is what i am trying to do.
once the user gets loggedIn, I show the user avatar along with a dropdown, with a logout button, when the user clicks the logout button, the following method is called.
```
logout(){
      this.$cookiz.remove('uid');
      this.$cookiz.remove('token');
      this.$cookiz.remove('ua');
      this.$cookiz.remove('userType');
      this.$cookiz.remove('userName');
      location.reload();
    },
```

**Comment by microcipcip** [comment]
But how do you set them? Can I see an example for some of those values? Also, are you using Nuxt Generate or are you running a proper server?

**Comment by maverickpravin** [comment]
@microcipcip 
```
if (response.data.success == true) {
            const token = response.data.token
            const name = response.data.firstName
            const uid = response.data.crossid
            const userAvtar = response.data.userImg   
            var payload = {
              token: token,              
              uid: uid,
              name: name
            }
            // clients
            this.$cookiz.set('token', response.data.token, {
              path: '/',
              domain: config.cookieURL,
              maxAge: 60 * 60 * 24 * 1
            })
            this.$cookiz.set('ua', response.data.userImg, {
              path: '/',
              maxAge: 60 * 60 * 24 * 1,
              domain: config.cookieURL,
            })
            this.$cookiz.set('uid', response.data.crossid, {
              path: '/',
              domain: config.cookieURL,
              maxAge: 60 * 60 * 24 * 1
            })
            this.$cookiz.set('userType', response.data.userType, {
              path: '/',
              domain: config.cookieURL,
              maxAge: 60 * 60 * 24 * 1
            })
            this.$cookiz.set('userName', response.data.firstName, {
              path: '/',
              domain: config.cookieURL,
              maxAge: 60 * 60 * 24 * 7
            })
            location.reload()
            this.$refs.myModalRef.hide()
             } 
            else {
            this.btnText = 'Sign In'
          }
        })
```

**Comment by microcipcip** [comment]
Oh I see now! I never set the domain, I think when you delete the cookie you have to set the domain there as well, but I haven't added that functionality, I'll have to change the script for that. Is setting the domain necessary?

**Comment by maverickpravin** [comment]
@microcipcip 
So you want me to explicitly mention the `domain` while removing the `cookies `?

**Comment by microcipcip** [comment]
You either remove `domain` when you set them, or I have to patch the delete to allow specifying the `domain` there, otherwise when you remove, the cookie plugin doesn't know from which domain you want it to remove from. 

Note that if the domain is external it may not even work for security reasons. I am not a cookie expert though, so not sure about this.

**Comment by maverickpravin** [comment]
@microcipcip  
As per my experience every cookie plugin offers the feature to explicitly remove the cookies from a specified domain, i think you should add it.
TIA

**Comment by microcipcip** [comment]
Please give me some time to fix it, I'll get back to you in 1/2 hours with the patch. I am currently busy :)

**Comment by maverickpravin** [comment]
Sure. Thank you for being receptive :)

**Comment by microcipcip** [comment]
NP :)

**Comment by microcipcip** [comment]
@maverickpravin I have been reviewing the code and I think that passing the domain in the remove is actually already supported, can you try if it works?

**Comment by maverickpravin** [comment]
Working!..... Thank You

**Comment by microcipcip** [comment]
Glad it worked, BTW you can refactor your code using `setAll` to make it smaller:
```
  const opts = {
    path: '/',
    domain: config.cookieURL,
    maxAge: 60 * 60 * 24 * 1
  }

  const cookieList = [
    {name: 'token', value: token}, opts,
    {name: 'ua', value: ua}, opts,
    {name: 'uid', value: uid}, opts,
    {name: 'userName', value: name}, opts,
  ] 
  
  this.$cookiz.setAll(cookieList)
```
