### ISSUE TITLE
Cannot read property '$cookies' of undefined

### ISSUE THREAD

**Issue by FreddyCrugger** [microcipcip/cookie-universal#24]
Hello,

Nuxt-config.

 modules: [
    'bootstrap-vue/nuxt',
    '@nuxtjs/pwa',
    'cookie-universal-nuxt',
    '@nuxtjs/toast',
  ],

Using NUXT 2.4.5
cookie-universal-nuxt: "^2.0.14",

I checked the other issues but could not find any answers that worked for me. 

I created a middleware in NUXT and added this code:
```
export default function () {
  const CookieIsLoggedIn = this.$cookies.get('isLoggedIn');
  const CookieAccessToken = this.$cookies.get('accessToken');
  const CookieRid = this.$cookies.get('rid');

  if ((CookieIsLoggedIn === true) && (CookieAccessToken !== undefined) && (CookieRid !== undefined)) {
    commit('isLoggedIn', CookieIsLoggedIn);
    commit('setToken', CookieAccessToken, CookieRid);
  } else {
    commit('isLoggedIn', false);
    this.$cookies.removeAll();
  }
```

Unfortunately when I run the command "nuxt" i get this error:
`Cannot read property '$cookies' of undefined`

I am only trying to get the cookies from the client side.

I forgot to mention that your cookie plugin works well within my vuex store, it is just in the middleware folder that it does not working.

Thank you.

**Comment by microcipcip** [comment]
The key `this` doesn't work within the middleware folder, you've got to replace it with app instead:
```
export default function ({ app }) { // added app here
  const CookieIsLoggedIn = app.$cookies.get('isLoggedIn');
  const CookieAccessToken = app.$cookies.get('accessToken');
  const CookieRid = app.$cookies.get('rid');
  // etc...
}
```

**Comment by microcipcip** [comment]
@FreddyCrugger did you manage to fix it with my suggestion?

**Comment by microcipcip** [comment]
@FreddyCrugger I'll close this for now since I haven't got any reply, please feel free to open it again if you feel this hasnt' be solved.

**Comment by Manouher** [comment]
Hello, I'm new on nuxt I have the same problem on the state,
`export default () => ({
  user_conf: this.$cookies.get('config-app'),
})`,

**Comment by microcipcip** [comment]
@Manouher you can't use `this` keyword in that way, with the arrow function you'll lose the context.

**Comment by xreider** [comment]
I have the samy issue

```
export default function(context) {
  const all = context.app.$cookies.getAll()
  console.log(all)
}
```

got **{}**

**Comment by microcipcip** [comment]
@xreider did you set any cookie? Where is that code running? I need some context.

**Comment by xreider** [comment]
> @xreider did you set any cookie? Where is that code running? I need some context.

I suppose my app has issues, because context hasn't req. And I do not know why. In other app your script goes well.

**Comment by microcipcip** [comment]
@xreider but where are you running the code? Is that a plugin, a middleware, or vuex init, etc?
