### ISSUE TITLE
TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.

### ISSUE THREAD

**Issue by sapfear** [microcipcip/cookie-universal#26]
Hi. Not building with actual TS version.

**Comment by sapfear** [comment]
PR is created

**Comment by Borisstoy** [comment]
Same issue here, can it merged?

**Comment by microcipcip** [comment]
@sapfear @Borisstoy Can you download the latest version and let me know if the merged fixed the issue for you? Haven't got a typescript project at hand right now :)

**Comment by Borisstoy** [comment]
Will do asap :) let me til Monday to give you some feedback. Appreciate the quick réaction. Thanks a lot!

**Comment by Borisstoy** [comment]
@microcipcip , tested in production, working perfectly 👌

**Comment by microcipcip** [comment]
@Borisstoy Thanks for getting back to me, happy everything is working :)
