### ISSUE TITLE
Adding Typescript Definitions

### ISSUE THREAD

**Issue by SanjayBanjade** [microcipcip/cookie-universal#28]
I added typescript definition to `nuxt.config.ts`. However, it throws me error saying `Property $cookies doesn't exists`.

Here's my `tsconfig.json`:
````
{
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "moduleResolution": "node",
        "lib": ["esnext", "esnext.asynciterable", "dom"],
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "allowJs": true,
        "sourceMap": true,
        "strict": false,
        "allowSyntheticDefaultImports": true,
        "noImplicitAny": false,
        "noEmit": true,
        "baseUrl": ".",
        "resolveJsonModule": true,
        "paths": {
            "~/*": ["./*"],
            "@/*": ["./*"]
        },
        "types": [
            "@nuxt/vue-app",
            "@types/node",
            "@nuxtjs/axios",
            "cookie-universal-nuxt"
        ]
    }
}
````

Please help.

**Comment by microcipcip** [comment]
@SanjayBanjade Is the error coming from typescript or from javascript? Are you actually using cookie-universal in the app already, or it is giving you errors by just adding it to the project?

**Comment by SanjayBanjade** [comment]
I installed it. And when I do `this.$cookies.set()`, then nuxt gave me that error.

**Comment by microcipcip** [comment]
@SanjayBanjade I need more info, as `this` sometimes is not accessible from middleware, can you share a snippet of code and tell me where you are using it? Also, did you add cookie-universal-nuxt to nuxt config file?

**Comment by microcipcip** [comment]
@SanjayBanjade I am closing this issue as I am not receiving any feedback. Let me know if you are still experiencing this error.
