### ISSUE TITLE
Issues with this module

### ISSUE THREAD

**Issue by ThatTonybo** [microcipcip/cookie-universal#30]
I've started to use this module, and have a middleware function for logging in. Currently, this is what I'm trying to use:
```js
this.$cookies.set('user', context, {
    maxAge: 604800000
});
```
It seems nothing happens after this, not the redirect, not the console logs, nothing.

I'm also trying to use this in my `Navbar.vue` component to get the user and set the user display/login display:
```js
<template>
    <div>
        <div class="contain navbar">
            <nuxt-link class="item logo" to="/">
                Website
            </nuxt-link>
            
            <nuxt-link class="item" to="/about">About</nuxt-link>

            <div class="right">
                <template v-if="!user">
                    <nuxt-link class="item" to="/login">Login</nuxt-link>
                </template>
                <template v-else>
                    <nuxt-link class="item" to="/user">{{ user.username }}</nuxt-link>
                </template>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    mounted () {
        const user = this.$cookies.get('user');
        
        if (!user) {
            return { user: null }
        } else {
            return { user }
        }
    }
}
</script>
```
But that doesn't work either.

Can I get some help with this?

**Comment by microcipcip** [comment]
@ThatTonybo your middleware code doesn't look right. Nuxt doesn't expose the `this` keyword inside a middleware, you have to use `app` instead. Try a code like this instead:

```
export default ({ app, context }) => {
  app.$cookies.set('user', context, {
    maxAge: 604800000
  });
}
``` 

Your second example looks all right, obviously is not finding anything because the middleware is failing.

**Comment by ThatTonybo** [comment]
@microcipcip Tried this and it seems to be a bit better maybe, but still no results or redirects. I'm also still getting this on the load of any page:
```
 ERROR  [Vue warn]: Property or method "user" is not defined on the instance but referenced during
render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Navbar> at components/Navbar.vue
       <Pages/callback.vue> at pages/callback.vue
         <Nuxt>
           <.nuxt/layouts/default.vue> at .nuxt/layouts/default.vue
             <Root>
```
I'm not too sure if it'd help also, but I use Discord oauth2, so mind the mess but here's the full callback [here](https://hasteb.in/alafavar.js).

**Comment by microcipcip** [comment]
@ThatTonybo you're not setting the user properly, I thought you were testing it, there is a basic concept in Vue for passing variables to the template, you have to pass them through the data object.

```
export default {
    data () { 
      return { 
        user: '' 
      }
    },
    mounted () {
        this.user = this.$cookies.get('user');
    }
}
```

**Comment by ThatTonybo** [comment]
Ah ok, I'm an idiot, thanks a lot! (I'm actually very new to Vue so)

**Comment by microcipcip** [comment]
@ThatTonybo NP! Everyone has to start from somewhere :) Good luck with your Vue journey ;)

**Comment by ThatTonybo** [comment]
@microcipcip Hey, sorry for referencing this again, but is the `set` function wrong here?
```js
app.$cookies.set('discord-user', context/*its an object*/, {
    maxAge: 604800000
});
```

I can console.log the function fine:
![image](https://user-images.githubusercontent.com/28176227/60639928-faea7400-9e67-11e9-860a-dc212367aa38.png)

But anything after, including if I try to console.log the set function while using it does nothing at all. Is this my code or something else?

**Comment by microcipcip** [comment]
@ThatTonybo the set function doesn't return anything, that's why you don't see anything. However, if you check your cookies in the browser dev tools, you should see a cookie being set.

If you want to check what has been set you have to use the get method `app.$cookies.get('discord-user')`.

**Comment by ThatTonybo** [comment]
Alright, makes sense. And accessing the cookies is fine through `app` in route middleware, but how would I access them in server middleware?

(mine is using express)

**Comment by microcipcip** [comment]
Good question, if `app` is not available you have to use the base version of cookie-universal instead of cookie-universal-nuxt, then you use it as follows:
```js
// Import the library after installing it with `npm i cookie-universal`
const Cookies = require('cookie-universal')

export default function (req, res, next) {
  // Initialize the library providing it with the required `req` and `res` objects.
  const cookies = Cookies(req, res)

  // Use it!
  cookies.set('cookie-name', 'cookie-value')
  next()
}
```

If you are writing multiple middlewares and don't want to initialize the cookies library in each middleware, you can probably create a middleware (and add it as first middleware in `nuxt.config`) just for the cookie library initialization and expose it as a variable in the `req` object, for example:
```js
const Cookies = require('cookie-universal')
export default function (req, res, next) {
  req.universalCookies = Cookies(req, res)
  next()
}
```
Then you should be able to use it in all other routes like this:
```js
export default function (req, res, next) {
  req.universalCookies.get('my-cookie')
  next()
}
```

**Comment by ThatTonybo** [comment]
And this will connect with the nuxt version front-end to provide the same data, right? Looks good though, I'll give it a try.

**Comment by microcipcip** [comment]
@ThatTonybo That's right, it will actually work with any frontend, not just with Nuxt.
