### ISSUE TITLE
why? app.$cookies is undefined in nuxt

### ISSUE THREAD

**Issue by jasonLaw1015** [microcipcip/cookie-universal#33]
my code:
  async nuxtServerInit({ commit }, { req, app }) {
    global_.webUrl = req.headers.host;

    app.$cookies.set('web_url', req.headers.host);
}

result:

TypeError
Cannot read property 'set' of undefined

**Comment by microcipcip** [comment]
@jasonLaw1015 I think you are getting `app` from the wrong object, try this:
```
async nuxtServerInit({ app, commit }, { req }) {
  global_.webUrl = req.headers.host;
  app.$cookies.set('web_url', req.headers.host);
}
```

**Comment by jasonLaw1015** [comment]
> @jasonLaw1015 I think you are getting `app` from the wrong object, try this:
> 
> ```
> async nuxtServerInit({ app, commit }, { req }) {
>   global_.webUrl = req.headers.host;
>   app.$cookies.set('web_url', req.headers.host);
> }
> ```

I did what you did, but it still didn't work.

so, That's the only way I can use it。like:

` async nuxtServerInit({ app, commit }, { req, res, route, redirect }) {
      const cookies = require('cookie-universal')(req, res);
      cookies.set('web_url', req.headers.host);
}`

**Comment by microcipcip** [comment]
Oh wait, did you install `cookie-universal` instead of `cookie-universal-nuxt`?

**Comment by jasonLaw1015** [comment]
> Oh wait, did you install `cookie-universal` instead of `cookie-universal-nuxt`?

yes，i  am using cookie-universal.

**Comment by microcipcip** [comment]
You have yo use `cookie-universal-nuxt`, [see docs here](https://github.com/microcipcip/cookie-universal/tree/master/packages/cookie-universal-nuxt).

**Comment by jasonLaw1015** [comment]
"app.$cookies is undefined in nuxt ?"
The problem arises in cookie-universal-nuxt@2.0.16 of situation

**Comment by microcipcip** [comment]
Are you able to access the @cookies library in the client or on a standard server middleware?

Are you working with Nuxt Generate mode or just normal dev mode? Several users had bugs with this cookie library when using Nuxt Generate.

**Comment by jasonLaw1015** [comment]
thank you! brother

**Comment by microcipcip** [comment]
What was the issue?
