### ISSUE TITLE
 Encryption functionnality ?

### ISSUE THREAD

**Issue by usb248** [microcipcip/cookie-universal#35]

**Comment by microcipcip** [comment]
Hi @usb248, unfortunately don't know how encrypted cookies works and I have never used them. 

If you have any idea of how it would work without disrupting the current API let me know and I may consider implementing it.

**Comment by usb248** [comment]
@microcipcip look : https://github.com/mozilla/node-client-sessions/

**Comment by microcipcip** [comment]
@usb248 this seems quite a complicated implementation, also AFAIK `node-client-sessions` lib is already doing what you need, so I don't think I will add that to this library.

**Comment by kgrosvenor** [comment]
If you want secure cookies, we could use httpOnly and secure flags, isn't this just to do with node sessions and not so much cookies?

**Comment by usb248** [comment]
Sometimes we want simply obfuscate data in cookie. And if we want manage session client side only, it’s relevant

**Comment by rchl** [comment]
@usb248 AFAIK there is no way to securely encrypt cookies on the client as you would then need to expose the secret also. So this request doesn't seem feasible.

**Comment by usb248** [comment]
@rchl 

> you would then need to expose the secret also
let me doubt it.
You can decrypt/edit/read etc... cookie only backend side and expose this decrypted cookie on client side without include secret in bundle client side.

**Comment by rchl** [comment]
Yes, but that would completely change the way this package is designed to work. You would no longer be able to just change/add/remove cookie directly in client-only fashion. You would always have to do a roundtrip to the server and that would be against the philosophy of this package and would certainly be a breaking change.

**Comment by usb248** [comment]
Yes I agree with you but i read 

> You can use cookie-universal to set, get and remove cookies in the browser, **node**, connect and express apps.

So for me, it was possible but if encrypted, exclude client side management for avoid sharing secret in client side.
