### ISSUE TITLE
Update cookie dependency version

### ISSUE THREAD

**Issue by TapanVaishnav** [microcipcip/cookie-universal#48]
@microcipcip Hi, we have been trying to add support for `SameSite` cookie option for our repos. [link](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html)
But for some cases, we want to enforce the `None` value for `SameSite` option which got supported only from `cookie-0.4.0` [link](https://github.com/jshttp/cookie/blob/master/HISTORY.md), as this is the only update in the latest version, we hope that it's not much trouble to update the `cookie` dependency for [cookie-universal-nuxt](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal-nuxt/package.json#L23). 
What do you think?
Of course, I would be more than happy to contribute to the project(if needed).

**Comment by microcipcip** [comment]
Hi @TapanVaishnav, I wasn't aware that this feature was added to the cookie library, I'll have a look at it!

**Comment by microcipcip** [comment]
@TapanVaishnav ok I've updated it, let me know if this fixes your issue ;)

**Comment by TapanVaishnav** [comment]
@microcipcip Hi, thanks for your quick response but I was hoping to bump [this](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal-nuxt/package.json#L23) up to `0.4.0`

**Comment by microcipcip** [comment]
@TapanVaishnav I did change it, that is the latest version, see here: https://www.npmjs.com/package/@types/cookie

**Comment by TapanVaishnav** [comment]
> @TapanVaishnav I did change it, that is the latest version, see here: https://www.npmjs.com/package/@types/cookie
> 
> As for the Cookie version, now is at `0.4.0` as you can [see here](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal/package.json#L35).

Ahh, ok, my bad. Thanks for your quick response and patch. 🙇

**Comment by microcipcip** [comment]
NP ;)
