### ISSUE TITLE
IE11 + SCRIPT1003: Expected ‘:’ error

### ISSUE THREAD

**Issue by swdbo** [microcipcip/cookie-universal#49]
Hey,

It seems your package breaks on IE11.
Didn't look further but it can just be a babel polyfill problem.

![Screenshot 2019-12-11 at 17 53 12](https://user-images.githubusercontent.com/8600049/70642396-6cacc200-1c3f-11ea-8138-6eddd4915075.png)
![Screenshot 2019-12-11 at 17 53 39](https://user-images.githubusercontent.com/8600049/70642398-6cacc200-1c3f-11ea-9e57-f2bfc14fdeca.png)

**Comment by microcipcip** [comment]
Hi @swdbo, how do you know that is this library that break IE11? I am currently compiling it to work with IE11 and I've used it in multiple projects, please make sure that it is my library that breaks IE11 and if it does, let me know exactly which function is causing you issues.

**Comment by swdbo** [comment]
@microcipcip
You are right, it was from my side
My apologies, thanks four your help !
