### ISSUE TITLE
Error running nuxt generate

### ISSUE THREAD

**Issue by timrijkse** [microcipcip/cookie-universal#5]
When running `npm run generate` the following error occurs:

```
Cannot detect env, something went wrong!
```

I'm using `nuxt 1.4.0`

**Comment by microcipcip** [comment]
My bad, I haven't tested it with Nuxt generate, I only tested with the node server, I'll have a look.

**Comment by timrijkse** [comment]
Thanks! I forked your package and commented the error throwing but then I have a second error. It might help you :)

```
 TypeError: argument str must be a string
```

**Comment by microcipcip** [comment]
I think that during the compilation process the plugin is unable to recognise the environment, I need to find a solution ;p

**Comment by microcipcip** [comment]
Try to change these lines for now, let me know if it works.

From this...
```
  const isClient = typeof document === 'object' && typeof document.cookie === 'string'
  const isServer = (() => {
    if (
      typeof req === 'object' &&
      typeof res === 'object' &&
      typeof module !== 'undefined'
    ) return true
})()
```
To this:
```
const isClient = true
const isServer = false
```

**Comment by timrijkse** [comment]
Thanks for the quick response, that would work for `npm run generate`. But unfortunately not for local development I think (`npm run dev`)

**Comment by timrijkse** [comment]
Cool! When I find something I'll let it know. Any idea about the other error? (When I comment the try/catch)

**Comment by microcipcip** [comment]
Yeah I think it is because isClient and isServer are both false so getHeaders doesn't return anything

**Comment by microcipcip** [comment]
https://nuxtjs.org/guide/release-notes#features I think process.static is the key here
Maybe this could work:
```
const isClient = (
  (typeof document === 'object' && typeof document.cookie === 'string') ||
  (process && process.static) // basically if it is static generated, this should return true?
)
```

**Comment by microcipcip** [comment]
@timrijkse try to update to the latest....it should work now, if an env is not found I assume it is node...it kind of sucks but I couldn't find another fix. Hopefully it will work for you.
