### ISSUE TITLE
option expires in invalid

### ISSUE THREAD

**Issue by mortezasabihi** [microcipcip/cookie-universal#51]
when i use expiration in my code:
```
 this.$cookies.set('cookie-consent', this.cookieConsent, {  expires: new Date().getFullYear() + 1 })
```

i get this error message:
```
option expires in invalid
```

**Comment by microcipcip** [comment]
Hi @mortezasabihi, the reason that you are unable to set it is that expires according to both this library documentation and [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/document/cookie#Write_a_new_cookie), has to be a proper `date` object. When you sum `new Date()` with `1`, you are transforming from `date` format to `number` format. A proper date to pass would be something like this `Thu, 01 Jan 2019 00:00:00 GMT`. I usually don't use expires as I find maxAge easier to use as there I can use a number instead (in seconds), for example: `maxAge: 60*60*24` would make the cookie expire in 1 day.

Hope this helps you fix your problem.

**Comment by microcipcip** [comment]
You can of course set expires with the help of a library like `date-fns` or with a function like this:
```
const addYears = (yearsToAdd = 1) => {
  const date= new Date();
  const newYear= date.getFullYear() + yearsToAdd
  return new Date(date.setFullYear(newYear));
}

 this.$cookies.set('cookie-consent', this.cookieConsent, {  expires: addYears(1) })
```
