### ISSUE TITLE
Error in types with typescript 3.7

### ISSUE THREAD

**Issue by rchl** [microcipcip/cookie-universal#52]
In my code I do something like:
```
import CookieUniversal from 'cookie-universal';

class Foo {
    constructor() {
        this.cookieStorage = CookieUniversal(this.context.req, this.context.res);
    }
}
```

and that triggers a Typescript error:
```
Declaration emit for this file requires using private name 'ICookie' from module '"/../node_modules/cookie-universal/types/index"'. An explicit type annotation may unblock declaration emit.
```

I won't claim that I fully understand it, but I believe it means that `ICookie` is required to be public/exported if I want to assign it to a variable/property and use it later.

**Comment by microcipcip** [comment]
@rchl thanks for your contribution, your PR has been merged, you can update to the latest version to access your typescript changes :)
