### ISSUE TITLE
Cannot remove Falsy cookies

### ISSUE THREAD

**Issue by Heziode** [microcipcip/cookie-universal#58]
I trying to remove "falsy" cookies (cookies that contains `0`, or `false`), but I cannot.

I think this is due to:

https://github.com/microcipcip/cookie-universal/blob/a703d5d57b6a03bd8531482b0fc4b768cd84d376/packages/cookie-universal/index.js#L89

Current workaround: set a non "falsy" value to be removable.

**Comment by microcipcip** [comment]
@Heziode can I see the code you've used for setting up the cookie?

**Comment by Heziode** [comment]
Example from my foss project:

https://github.com/FOE-Tools/FOE-Tools.github.io/blob/8bb36dea80656ea164b1b4d320aa6cde3db31fea/layouts/_default/script.js#L340-L351

I have some cookies that can have a "falsy" value depending of user preferences.

**Comment by microcipcip** [comment]
Hi @Heziode, I have updated the cookie library with the fix. Can you please close this issue if it works?

**Comment by Heziode** [comment]
Thank's @microcipcip, it works.
