### ISSUE TITLE
[Feature Request]: add typescript definitions.

### ISSUE THREAD

**Issue by chanlito** [microcipcip/cookie-universal#6]
It will be helpful in some IDEs.

**Comment by microcipcip** [comment]
@chanlito I don't use Typescript but I accept pull requests if anybody is willing to do it.

**Comment by Hiswe** [comment]
@chanlito I've done something like that for the types

https://github.com/Hiswe/a-count/blob/master/acount-nuxt/types/nuxt.d.ts#L57-L83

And also

https://github.com/Hiswe/a-count/blob/master/acount-nuxt/types/vue-shims.d.ts#L8-L13

Not sure if it's good enough. Still new to typescript…

**Comment by blowsie** [comment]
+ I dont use typescript either, but my ide understands it 👍

**Comment by microcipcip** [comment]
@blowsie Can you please try the latest version and let me know if it works?

**Comment by blowsie** [comment]
Works a charm 👍

**Comment by microcipcip** [comment]
Amazing :)
