### ISSUE TITLE
argument val is invalid

### ISSUE THREAD

**Issue by JBustin** [microcipcip/cookie-universal#60]
Hello,

In production environment, with cookie-universal-nuxt, sometimes a bug happens with this stacktrace : 

```
TypeError: argument val is invalid
    at Object.n [as serialize] (/srv/nodejs/20.5.1-RC/node_modules/cookie-universal/dist/cookie-universal-common.js:1:3447)
    at t.headers.Cookie.Object.keys.reduce (server.js:1:476394)
    at Array.reduce (<anonymous>)
    at t.interceptors.request.use.t (server.js:1:476347)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I think that is cookie library that raised this error here : https://github.com/jshttp/cookie/blob/b223a3447666fbdabc0ff8b3583081c22fd7c4e7/index.js#L116

But I fail to reproduce the bug in dev/local environment, I'm a bit lost with the dist, the lib, the build, and finally with the sources actually executed.

Is there a good way to investigate this bug ?
Do I check and exclude some misformatted cookies ?
Should I try ... catch my uses of cookie-universal-nuxt `set` or `get` methods ?

Regards

**Comment by microcipcip** [comment]
Hi @JBustin, I think it could make sense to ask for help in the [cookie library repo](https://github.com/jshttp/cookie/) as I don't fully understand the code it is using for serializing. 

I have tried to create a demo in codesandbox and pass invalid values but I am unable to make it throw that specific error. 

If you `console.log` the value you use in the `set` method it may help debugging it, but it is better if you report it in that repo anyway as I don't believe is an error specific to this library. 

Maybe there is a unicode char that is not recognized, but this is a wild guess.

**Comment by JBustin** [comment]
@microcipcip thank you for your suggestion.
I currently succeed to reproduce.
I will be able to log and to fix the problem.
