### ISSUE TITLE
vue.d.ts doesn't honor `alias

### ISSUE THREAD

**Issue by xinbenlv** [microcipcip/cookie-universal#63]
file: https://github.com/microcipcip/cookie-universal/commit/fcee0e1ae6eadf2e86fdbf2a6362bfdfda21722e

Hi **[vue.d.ts](packages/cookie-universal-nuxt/types/vue.d.ts)** doesn't seem to honor `alias`

```javascript
// tsconfig.json
module.exports = {
 modules: [
    //...,
    ['cookie-universal-nuxt', { alias: 'cookiez' }],
    //...
]
}
```

```typescript
// some-comp.vue 

// <script lang="ts">
  import { Vue, Component, Prop } from 'vue-property-decorator';
  @Component
  export default class SomeComp extends Vue {
    someFn (t) {
      let gaId = this.$cookiez.get("_ga");
    }
  }
// </script>

```

**Comment by microcipcip** [comment]
Sorry @xinbenlv I have no idea how to make this work. I am afraid that for now you'll have to avoid using the alias with Typescript. If there is anybody that knows how to fix this, I'll gladly accept a PR.

**Comment by xinbenlv** [comment]
Like-wise, I think the author of `vue.d.ts` might know better.
I found some references might work
- Blog post: [Can I dynamically add properties to an interface in Typescript?](https://www.vincecampanale.com/blog/2018/01/12/dynamically-properties-to-typescript-interfaces/) and it's section `Dynamic keys`.

```typescript
// file: https://github.com/microcipcip/cookie-universal/blob/1443a3d12325fb58fc9c62e3781b4e4adae206f3/packages/cookie-universal-nuxt/types/vue.d.ts#L8


```
shall reflect 

```javascript
// file: https://github.com/microcipcip/cookie-universal/blob/48486402fe1b23e3ea2ef315df3363600ff273a1/packages/cookie-universal-nuxt/lib/templates/cookie-universal-nuxt.js
import cookieUniversal from 'cookie-universal'

export default ({ req, res }, inject) => {
  const options = <%= JSON.stringify(options, null, 2) %>
  inject(options.alias, cookieUniversal(req, res, options.parseJSON))
}
```

Adding the author @Hiswe and @darthf1 for their wisdom

**Comment by microcipcip** [comment]
Thanks a lot for investigating this. I think that because Typescript is statically analized the alias functionality cannot be implemented unless we accept any key as if it were a `NuxtCookies`. For instance, this may work but would be quite bad:
```
interface Vue {
   [key: string]: NuxtCookies;
}
```

I think another quick fix that could actually work would be defining the NuxtCookies interface declaration manually. 

However, if you manage to, I will be very happy to accept your PR.

**Comment by xinbenlv** [comment]
A quick fix I did, more of a hack, is to declare the alias within the Single-File Component

```typescript
    import {Component, Prop, Vue} from 'vue-property-decorator';

    @Component
    export default class SomeComponent extends Vue {
       //...   
       $cookiez: NuxtCookies;
       //...
    }
```

See this file: https://github.com/google/wikiloop-battlefield/blob/0c89ad365742ce6fe803fb48178ec5c8f1771a8d/components/ActionPanel.vue#L65

And it works. 

And this bug is to look for more long term solution.

**Comment by microcipcip** [comment]
If you can also [define it globally here](https://github.com/google/wikiloop-battlefield/blob/0c89ad365742ce6fe803fb48178ec5c8f1771a8d/vue-shim.d.ts).

```
declare module "vue/types/vue" {
  import { NuxtCookies } from 'cookie-universal-nuxt'

  interface Vue {
    $cookiez: NuxtCookies;
  }
}

declare module 'vuex/types/index' {
  import { NuxtCookies } from 'cookie-universal-nuxt'

  interface Store<S> {
    $cookies: NuxtCookies
  }
}
```
