### ISSUE TITLE
Expire Date is Too Short

### ISSUE THREAD

**Issue by BerkanSezer** [microcipcip/cookie-universal#68]
Hello, i'im adding any cookie like that;
```
this.$cookies.set('COOKIE_KEY', this.$store.state.COOKIE_VALUE, {
    path: '/',
    expires: new Date(new Date().getTime() + 1000 * 3600 * 24 * 30),
});
```

but this is adding my cookie with wrong times, maximum 7 days.
If i add smaller than 7 days it works, but not working bigger than 7.
I didn't solve this issue.

nuxt.config.js 
```
...
modules: [
    ['cookie-universal-nuxt', {path: '/'}]
],
...```

**Comment by microcipcip** [comment]
Hi @BerkanSezer unfortunately I am unable to reproduce it, I have just tried with Chrome and Firefox with the following code...
```
cookies.set('test', 'some value', {
    path: '/',
    expires: new Date(new Date().getTime() + 1000 * 3600 * 24 * 30)
  })
```

...and I got back in both browsers expiry date of `Sun, 28 Jun 2020 11:27:29 GMT`. 

Is it possible that you changed your OS date or that it is reading it server side with SSR and your server has wrong date there? What's the console output when you do `console.log(new Date(new Date().getTime() + 1000 * 3600 * 24 * 30))`?

Unrelated, but note that your nuxt config is wrong, there is no such thing as path config that can be passed there. The only options available are `alias` and `parseJSON`.

**Comment by BerkanSezer** [comment]
`console.log(new Date(new Date().getTime() + 1000 * 3600 * 24 * 30))` returns `Sun Jun 28 2020 16:08:35 GMT+0300 (GMT+03:00)` in my Browser.
OK, i'll change my nuxt.config.js file but this library still not working.
By the way, i tried `maxAge: 1000 * 3600 * 24 * 30` instread of `expires` but there is no changes.

**Comment by microcipcip** [comment]
@BerkanSezer I am willing to help you, but since I am unable to reproduce it, I will need access to a demo if you are able to provide one. I find it hard to belive that there is an issue with the `expires` or `maxAge` code as that is using an external library used by thousands of devs, the issue must be somewhere else.
