### ISSUE TITLE
On production (https)  app.$cookies.get equals to undefined

### ISSUE THREAD

**Issue by yalondpsi** [microcipcip/cookie-universal#77]
Hi,
I cannot read a cookie when uploaded to server (firebase hosting).
It's working fine on my local machine

## code for the plugin settings (nuxt.config.js):
```
['cookie-universal-nuxt', { path: '/', secure: true, maxAge: 60 * 60 * 24 * 7 }]
```
## code when setting a cookie inside a page method:
```
onEng() {
      const cookieValObject = { lang: 'en' };
      this.$cookies.set('ldfjpotcmhgsel', cookieValObject );
      window.location.reload(true);
    }
```
## code in the middleware file when trying to get the cookie and getting undefined:
```
export default function({app}) {
     const language_cookie = app.$cookies.get('ldfjpotcmhgsel');
     console.log('cookie:', language_cookie); // I get undefined
}
```
Is it something wrong with the code?
I make secure to false when on dev machine (no ssl)
Thank you

**Comment by microcipcip** [comment]
Hi @yalondpsi, the problem with your code is that the plugin does not allow to set global config settings, if you check the documentation the only global settings you can pass are the `alias` and `parseJSON`. So you have to pass the options object in each call, or [do as I suggested here](https://github.com/microcipcip/cookie-universal/issues/64#issuecomment-616813222).

**Comment by yalondpsi** [comment]
Hi @microcipcip , 
Thank you for the answer. I will try again and let you know

**Comment by yalondpsi** [comment]
Hi again @microcipcip ,
Not working again on production.
I change the code inside the page method to:
```
    onEng() {
      const options = { path: '/', maxAge: 60 * 60 * 24 * 7, secure: true };
      const cookieValObject = { lang: 'en' };
      this.$cookies.set('ldfjpotcmhgsel', cookieValObject, options );
      window.location.reload(true);
    }
```
Few more details:
My domain is temporary a sub domain:
**https://name-2020.web.app**

When I look at Chrome developers tools -> Application, I see this:

![image](https://user-images.githubusercontent.com/14073961/90392565-c94a6180-e097-11ea-98dc-1dc085d93181.png)

and this:

![image](https://user-images.githubusercontent.com/14073961/90392671-00b90e00-e098-11ea-9dc8-70b97167b509.png)

What am I doing wrong?
Thank you for your help

**Comment by yalondpsi** [comment]
Hi @microcipcip,
Have you seen my answer 2 days ago?
Thanks

**Comment by yalondpsi** [comment]
Hi @microcipcip,

**Found the solution:**
The problem was caused by firebase hosting.
There are 2 restrictions regarding cookies with firebase hosting:

A cookie name must be **__session**
and in firebase functions, you should set the Cache-Control to private:

```res.setHeader('Cache-Control', 'private');```

**Comment by microcipcip** [comment]
@yalondpsi Sorry I totally missed your question. Glad that you managed to solve it.
