### ISSUE TITLE
I'm Offended.

### ISSUE THREAD

**Issue by lmf-git** [microcipcip/cookie-universal#79]
No usage docs?

**Comment by williamweckl** [comment]
This is a great library, instead of complaining you could open a pull request and help to improve. :)

**Comment by lmf-git** [comment]
> This is a great library, instead of complaining you could open a pull request and help to improve. :)

Learn to spot a joke. :)

P.s. my observation of an obvious flaw is contributing more than your defensive whining did.

**Comment by microcipcip** [comment]
@lmf-git sorry I missed your issue completely. There is extensive docs with examples, I guess you didn't click in the specific repositories? 
- Docs for [cookie-universal](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal).
- Docs for [cookie-universal-nuxt](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal-nuxt).
