### ISSUE TITLE
Cookies are unavailable in middleware

### ISSUE THREAD

**Issue by NMFES** [microcipcip/cookie-universal#81]
```
// nuxt.config.js
...
    modules: [
        ['cookie-universal-nuxt', , {parseJSON: false}],
    ],
    router: {
        middleware: 'i18n'
    },
...
```

```
// middleware/i18n.js
export default function ({app}) {
    console.log(app.$cookies.get('locale')); // returns empty
    console.log(app.context.ssrContext.req.headers.cookie); // returns valid cookie as a string ("locale=ru" in my case)
```

**Comment by ryanweal** [comment]
I am also seeing this issue in my Nuxt instance. When I am doing `npm run dev` it does not have any values. I can get the app.context.ssrContext value, and I can get a value to return in plugins. However I am not able to get it in middleware.

My site is going to be generated so I don't want to rely on the SSR attributes. I would much rather use this module but I feel like I am missing something.

**Comment by ryanweal** [comment]
I was eventually able to get this going. I think it was a combination of needing to completely restart the `npm run dev` process as well as disable the cache on my browser by using the network tab on dev tools.

I believe what was happening was a memory leak elsewhere in the application that was triggered by the changes I was making. At one point I had to restart the browser(!) so I believe it was related to my other components.

Hopefully this info helps out others as they begin working with this module!

**Comment by CHOMNANP** [comment]
I'm having the same issue.
