### ISSUE TITLE
get expire date

### ISSUE THREAD

**Issue by sajcics** [microcipcip/cookie-universal#85]
Hi. How I can get expire timestamp with get method of specific cookie? 
When I use get method I only get value of cookie but not defined options too (like expires, size).

**Comment by raminjafary** [comment]
There are use cases for which scheduling some tasks on the client depends on. It is not straightforward to implement since client only sends cookie name and value. 
@microcipcip I think there may be workarounds but don't know if it worth it. I can give it a try!

**Comment by microcipcip** [comment]
There is no browser API for that, you can't get that value, I guess they did it on purpose for security reasons. If you need that kind of information I suggest you save the data as an object and add the timestamp there yourself.
