### ISSUE TITLE
How use in vuex store

### ISSUE THREAD

**Issue by htchtc052** [microcipcip/cookie-universal#9]
if i try app.$cookie in nuxt vuex store have error undefined. How fix ?

**Comment by microcipcip** [comment]
by defauls it `app.$cookies` not `app.$cookie`. Is it just a typo maybe?

**Comment by microcipcip** [comment]
@htchtc052 did this solve your problem?

**Comment by turukawa** [comment]
Hi,

I'm going to reopen this issue as I have the same question. I'm attempting to store an external api response in a cookie and am struggling to figure out how to do so within the Nuxt store.

I'm new to Nuxt (and Vue.js) so many of the key concepts still go over my head.

In my `store` folder, I have a store.js file with the following action:

```
export const actions = {
  getResponse: ({ commit }, data ) => {
      axios.post(
        `http://some.url/some_request`
      ).then(( response ) => {
      var response_details = {
        response_variable: response.data.variable
      };
      commit("setResponse", response_details );
      app.$cookie.set("cookie", response_details , {
        path: '/',
        maxAge: 60 * 60 * 24 * 7
      });
    })
  }
}
```

However, `app` doesn't exist and throws an error. Every example I see says to access things this way, but I've not been able to figure out how to access the `app` context.

Thanks ...
