### ISSUE TITLE
IE11 get is undefined

### ISSUE THREAD

**Issue by chinggo** [microcipcip/cookie-universal#97]
Hello Microcipcip,

I am try to set、get  cookie in Nuxt Project 

the sample like this,

this.$cookies.set('token', '111111')
this.$cookies.get('token')

but when i look console this.$cookies.get('token') in the IE11, the value is always undefined and document.cookie have value or chrome、 firefox

here's my package.json

"dependencies": {
    "@fortawesome/fontawesome-free": "^5.15.2",
    "@nuxt/content": "^1.13.1",
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/date-fns": "^1.4.3",
    "@nuxtjs/dotenv": "^1.4.1",
    "@nuxtjs/proxy": "^2.1.0",
    "@types/js-cookie": "^2.2.6",
    "@types/lodash": "^4.14.168",
    "cookie-universal-nuxt": "^2.1.4",
    "default-passive-events": "^2.0.0",
    "element-ui": "^2.15.1",
    "highcharts": "^8.2.2",
    "intersection-observer": "^0.12.0",
    "jquery": "^3.5.1",
    "js-cookie": "^2.2.1",
    "lodash": "^4.17.21",
    "md5-typescript": "^1.0.5",
    "nuxt": "^2.15.2",
    "nuxt-polyfill": "^1.0.3",
    "nuxt-vuex-localstorage": "^1.2.7",
    "promise-polyfill": "8.2.0",
    "smoothscroll-polyfill": "^0.4.4",
    "url-polyfill": "^1.1.12",
    "vue-scrollto": "^2.20.0",
    "vue-slick": "^1.1.16",
    "vue-slick-carousel": "^1.0.6"
  },
  "devDependencies": {
    "@babel/runtime-corejs3": "^7.13.10",
    "@nuxt/types": "^2.15.2",
    "@nuxt/typescript-build": "^2.0.6",
    "@nuxtjs/pwa": "^3.3.5",
    "@types/jquery": "^3.5.5",
    "core-js": "^3.9.1",
    "cross-env": "^7.0.3",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-prettier": "^3.3.1",
    "fibers": "^5.0.0",
    "node-sass": "^5.0.0",
    "npm-build-zip": "^1.0.3",
    "prettier": "^2.2.1",
    "sass-loader": "^10.1.1",
    "vuex-module-decorators": "^1.0.1"
  }

and nuxt.config cookie-universal-nuxt plugin setting is by default setting

thanks you

**Comment by microcipcip** [comment]
Sorry for the delay, does it work fine in FF and Chrome?
